# Repositorio que será utilizado para gerar os arquivos.
- uses: Platane/snk@master
id: snake-gif
with: 
github_user_name:ianperesdarosa
git_out_path: dist/github-contribution-grid-snake.gif
git_out_path: dist/github-contribution-grid-snake.svg
